// @generated by protoc-gen-es v1.3.0 with parameter "target=ts"
// @generated from file canto/csr/v1/params.proto (package canto.csr.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * Params holds parameters for the csr module
 *
 * @generated from message canto.csr.v1.Params
 */
export class Params extends Message<Params> {
  /**
   * boolean to enable the csr module
   *
   * @generated from field: bool enable_csr = 1;
   */
  enableCsr = false;

  /**
   * decimal to determine the transaction fee split between network operators (validators) and CSR
   *
   * @generated from field: string csr_shares = 2;
   */
  csrShares = "";

  constructor(data?: PartialMessage<Params>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = "canto.csr.v1.Params";
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: "enable_csr", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 2, name: "csr_shares", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ]);

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): Params {
    return new Params().fromBinary(bytes, options);
  }

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): Params {
    return new Params().fromJson(jsonValue, options);
  }

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): Params {
    return new Params().fromJsonString(jsonString, options);
  }

  static equals(a: Params | PlainMessage<Params> | undefined, b: Params | PlainMessage<Params> | undefined): boolean {
    return proto3.util.equals(Params, a, b);
  }
}

